.\"Created with GNOME Manpages Editor
.\"http://sourceforge.net/projects/gmanedit2

.\"Replace <program> with the program name, x with the Section Number
.TH <program> x "<date>" "" "Linux User's Manual"

.SH NAME
<program> \- program for...

..SH SYNOPSIS
.B <program>
.RI [ options ]
.br

.SH DESCRIPTION
This manual page explains the \fB<program>\fP program. The \fB<program>\fP program is for...

.SH OPTIONS
.IP \fB\-OPTION\fP
This option...

.SH NOTES

.SH "SEE ALSO"
