.TH lepton-conf 1 "May 12, 2021" "Lepton EDA" 1.0

.SH NAME
lepton-conf \- Lepton EDA configuration utility

..SH SYNOPSIS
.B lepton-conf
.RI [ options ]
.RI [ path ]
.br

.SH DESCRIPTION
This manual page explains the \fBlepton-conf\fR program.

.SH OPTIONS
.TP
\fB\-e\fR
Close window with 'Escape' key
.TP
\fB\-l\fR
Legacy mode: use geda*.conf configuration files
.TP
\fB\-m\fR
Do not warn about missing configuration files
.TP
\fB\-p\fR
Print default settings in the *.conf file format and exit
.TP
\fB\-r\fR
Restore last working directory
.TP
\fB\-h\fR
Show usage information
.TP
\fB\-v\fR
Show version information

.SH SEE ALSO
\fBlepton-cli\fR(1)
